# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "US/Eastern"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Rust
  - package-ecosystem: "cargo"
    directories:
      - "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "US/Eastern"
    # groups:
    #   cargo:
    #     patterns:
    #       - "*"
    #     update-types:
    #       - "minor"
    #       - "patch"

  # NPM / Node stuff
  - package-ecosystem: "npm"
    directories:
      - "/frontend"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "US/Eastern"
    groups:
      frontend:
        patterns:
          - "*"
        exclude-patterns:
          - "typescript"
        update-types:
          - "minor"
          - "patch"
